name: sre-actions/aws-ssm-parameter
description: Get AWS SSM parameter and set to environment variables
author: globis-org
inputs:
  data:
    description: Parameter keys and env var names (YAML)
    required: true
runs:
  using: 'node20'
  main: 'dist/main.js'
