engineStrict: true
minimumReleaseAge: 10080 # 1 week
minimumReleaseAgeExclude:
  - typescript
  - '@typescript/*'
  # Renovate security update: js-yaml@4.3.1
  - js-yaml@4.3.1

packages:
  - '*'

savePrefix: ''

# preinstall/install/postinstall スクリプトの実行を許可するかどうか
# デフォルトは false
allowBuilds:
  '@swc/core': true
  esbuild: true
  unrs-resolver: true
