minimumReleaseAge: 10080 # 1 week

packages:
  - '*'

savePrefix: ''

# preinstall/install/postinstall スクリプトの実行を許可するかどうか
# デフォルトは false
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  # Renovate security update: esbuild@0.28.1
  - esbuild@0.28.1
