name: sre-actions/terraform-lockfile-checker
description: Check if Terraform lockfile is commited
author: sys-gdp
inputs:
  pull-request-number:
    description: Pull request number
    required: true
    default: ${{ github.event.pull_request.number }}
  path-filters:
    description: Path filters to check (use `terraform` as key)
    required: true
    default: |
      terraform:
        - 'terraform/**'

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    - name: Filter changed path
      id: filter
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      with:
        list-files: json
        filters: ${{ inputs.path-filters }}

    - name: Check .terraform.lock.hcl is commited
      run: ${{ github.action_path }}/check.sh
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        FILES_JSON: ${{ steps.filter.outputs.terraform_files }}
        PR_NUMBER: ${{ inputs.pull-request-number }}
      if: steps.filter.outputs.terraform == 'true' && github.event_name == 'pull_request'
