name: sre-actions/terraform-lockfile-checker
description: Check if Terraform lockfile is committed
author: globis-org
inputs:
  pull-request-number:
    description: Pull request number
    required: true
    default: ${{ github.event.pull_request.number }}
  files:
    description: Files to check
    required: true
    default: |
      terraform/**
  files-ignore:
    description: Files to ignore
    required: true
    default: |
      **/modules/**

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Filter changed files
      id: filter
      uses: tj-actions/changed-files@e0021407031f5be11a464abee9a0776171c79891 # v47.0.1
      with:
        json: true
        write_output_files: true
        dir_names: true
        files: ${{ inputs.files }}
        files_ignore: ${{ inputs.files-ignore }}

    - name: Check .terraform.lock.hcl is committed
      run: ${{ github.action_path }}/check.sh
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        PR_NUMBER: ${{ inputs.pull-request-number }}
        JSON_PATH: .github/outputs/all_changed_and_modified_files.json
      if: steps.filter.outputs.all_changed_and_modified_files_count != '0' && github.event_name == 'pull_request'
