name: sre-actions/codeowners-validator
description:
author: globis-org
inputs:
  token:
    description: GitHub Token
    required: true
    default: ${{ github.token }}
  codeowners:
    description: Codeowners file
    required: true

runs:
  using: node20
  main: dist/index.js
