name: sre-actions/manifest-analyzer
description: Analyze kubernetes manifests
author: globis-org
inputs:
  base-dir:
    description: Base directory to analyze
    required: true
  head-dir:
    description: Head directory to analyze
    required: true
  k8s-version:
    description: Kubernetes version
    required: true
  artifact-name:
    description: Name of the artifact to upload (if specified, results will be uploaded)
    required: false
    default: ''
  artifact-retention-days:
    description: Number of days to retain the artifact
    required: false
    default: '7'

runs:
  using: composite
  steps:
    - uses: asdf-vm/actions/install@1902764435ca0dd2f3388eea723a4f92a4eb8302 # v4.0.0
      with:
        before_install: pwd; ls -la; cd ${{ github.action_path }}

    - id: kustomize
      run: ${{ github.action_path }}/kustomize.sh
      shell: bash
      env:
        BASE_DIR: ${{ inputs.base-dir }}
        HEAD_DIR: ${{ inputs.head-dir }}

    - id: dyff
      run: ${{ github.action_path }}/dyff.sh
      shell: bash
      env:
        BASE_DIR: ${{ inputs.base-dir }}
        HEAD_DIR: ${{ inputs.head-dir }}

    - id: lint
      run: ${{ github.action_path }}/lint.sh
      shell: bash
      env:
        BASE_DIR: ${{ inputs.base-dir }}
        HEAD_DIR: ${{ inputs.head-dir }}
        K8S_VERSION: ${{ inputs.k8s-version }}

    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const { promises: fs } = require('fs');
          const dyff = await fs.readFile('${{ steps.dyff.outputs.file }}', 'utf8');
          const lint = await fs.readFile('${{ steps.lint.outputs.file }}', 'utf8');
          await core.summary.addRaw(dyff).addEOL().addRaw(lint).write();
      if: always()

    - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.6.2
      with:
        name: ${{ inputs.artifact-name }}
        path: |
          ${{ steps.dyff.outputs.file }}
          ${{ steps.lint.outputs.file }}
        retention-days: ${{ inputs.artifact-retention-days }}
      if: always() && inputs.artifact-name != ''
