name: sre-actions/manifest-analyzer
description: Analyze kubernetes manifests
author: globis-org
inputs:
  base-dir:
    description: Base directory to analyze
    required: true
  head-dir:
    description: Head directory to analyze
    required: true
  k8s-version:
    description: Kubernetes version
    required: true
  artifact-name:
    description: Name of the artifact to upload (if specified, results will be uploaded)
    required: false
    default: ''
  artifact-retention-days:
    description: Number of days to retain the artifact
    required: false
    default: '7'

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@e3d7b8d67a7958d1207f6ed871e83b1ea780e7b0 # v3.3.1
      env:
        MISE_GLOBAL_CONFIG_FILE: ${{ github.action_path }}/mise.toml

    - id: kustomize
      run: ${{ github.action_path }}/kustomize.sh
      shell: bash
      env:
        BASE_DIR: ${{ inputs.base-dir }}
        HEAD_DIR: ${{ inputs.head-dir }}
        MISE_GLOBAL_CONFIG_FILE: ${{ github.action_path }}/mise.toml

    - id: dyff
      run: ${{ github.action_path }}/dyff.sh
      shell: bash
      env:
        BASE_DIR: ${{ inputs.base-dir }}
        HEAD_DIR: ${{ inputs.head-dir }}
        MISE_GLOBAL_CONFIG_FILE: ${{ github.action_path }}/mise.toml

    - id: lint
      run: ${{ github.action_path }}/lint.sh
      shell: bash
      env:
        BASE_DIR: ${{ inputs.base-dir }}
        HEAD_DIR: ${{ inputs.head-dir }}
        K8S_VERSION: ${{ inputs.k8s-version }}
        MISE_GLOBAL_CONFIG_FILE: ${{ github.action_path }}/mise.toml

    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const { promises: fs } = require('fs');
          const dyff = await fs.readFile('${{ steps.dyff.outputs.file }}', 'utf8');
          const lint = await fs.readFile('${{ steps.lint.outputs.file }}', 'utf8');
          await core.summary.addRaw(dyff).addEOL().addRaw(lint).write();
      if: always()

    - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: ${{ inputs.artifact-name }}
        path: |
          ${{ steps.dyff.outputs.file }}
          ${{ steps.lint.outputs.file }}
        retention-days: ${{ inputs.artifact-retention-days }}
      if: always() && inputs.artifact-name != ''
