name: sre-actions/manifest-analyzer
description: Analyze kubernetes manifests
author: sys-gdp
inputs:
  base-dir:
    description: Base directory to analyze
    required: true
  head-dir:
    description: Head directory to analyze
    required: true
  k8s-version:
    description: Kubernetes version
    required: true

runs:
  using: composite
  steps:
    - uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2
      with:
        tool_versions: |
          kustomize 5.0.1 # Argo CD v2.7.0
          kube-score 1.16.1
          kubeconform 0.6.1
          pluto 5.16.1
          dyff 1.5.8

    - id: kustomize
      run: ${{ github.action_path }}/kustomize.sh
      shell: bash
      env:
        BASE_DIR: ${{ inputs.base-dir }}
        HEAD_DIR: ${{ inputs.head-dir }}

    - id: dyff
      run: ${{ github.action_path }}/dyff.sh
      shell: bash
      env:
        BASE_DIR: ${{ inputs.base-dir }}
        HEAD_DIR: ${{ inputs.head-dir }}

    - id: lint
      run: ${{ github.action_path }}/lint.sh
      shell: bash
      env:
        BASE_DIR: ${{ inputs.base-dir }}
        HEAD_DIR: ${{ inputs.head-dir }}
        K8S_VERSION: ${{ inputs.k8s-version }}

    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const { promises: fs } = require('fs');
          const dyff = await fs.readFile('${{ steps.dyff.outputs.file }}', 'utf8');
          const lint = await fs.readFile('${{ steps.lint.outputs.file }}', 'utf8');
          await core.summary.addRaw(dyff).addEOL().addRaw(lint).write();
      if: always()
