name: sre-actions/lint-manifests
description: Lint kubernetes manifests
author: sys-gdp
inputs:
  env:
    description: Environment to lint
    required: true
  product:
    description: Product to lint
    required: false
    default: ''
  k8s-version:
    description: Kubernetes version
    required: true

runs:
  using: composite
  steps:
    - uses: asdf-vm/actions/install@6a442392015fbbdd8b48696d41e0051b2698b2e4 # v2.2.0
      with:
        tool_versions: |
          kustomize 4.5.7
          helm 3.10.1
          kube-score 1.16.1
          kubeconform 0.6.1
          pluto 5.16.1

    - run: ${{ github.action_path }}/lint.sh
      shell: bash
      env:
        ENV: ${{ inputs.env }}
        PRODUCT: ${{ inputs.product }}
        K8S_VERSION: ${{ inputs.k8s-version }}

    - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
      with:
        script: |
          const { promises: fs } = require('fs');
          const output = await fs.readFile('output.md', 'utf8');
          await core.summary.addRaw(output).write();
      if: always()
